apiVersion : apps/v1
kind: Deployment
metadata:
  name: sravanpipelinesjavascriptdocker 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sravanpipelinesjavascriptdocker
  template:
    metadata:
      labels:
        app: sravanpipelinesjavascriptdocker 
    spec:
      containers:
        - name: sravanpipelinesjavascriptdocker 
          image: myappaks.azurecr.io/sravanpipelinesjavascriptdocker
          ports:
          - containerPort: 8080